spring:
  data:
    redis:
      host: ""
  datasource:
    url: ""
    username: ""
    password: ""
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ""
            client-secret: ""
          google:
            client-id: ""
            client-secret: ""

app:
  bot:
    api-key: ""
  jwt:
    secret: ""
  external-api:
    balldontlie-api-key: ""

observability:
  loki-url: ""

secrets:
  cloudinary:
    cloud-name: ""
    api-key: ""
    api-secret: ""
  email:
    username: ""
  discord:
    token: ""
  telegram:
    token: ""
  pandascore:
    api-key: ""
  prometheus-url: ""
