spring.application.name=parallax-sports-spring

server.port=8084

spring.datasource.url=jdbc:h2:file:./data/parallax-sports-db;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.hibernate.ddl-auto=none

# La primera vez descomenado
# Una vez creada comento
#spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



